spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    password: 1234
    username: root
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test
      password: 1234
      username: root
    sub:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/lab
      password: 1234
      username: root


  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "user"
#    password: "1234"

  redis:
#    password: 4648
#    cluster:
#      nodes:
#        - localhost:7000
#        - localhost:7001
#        - localhost:7002

server:
  port: 8099
