spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    password: 1234
    username: root
    hikari:
      maximum-pool-size: 40

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true